Hangman game/basic version
CoreyGinnivan/devtrain pull request #1
Opened 2023-05-01 03:31 UTC by CoreyGinnivan

<img width="1415" alt="Screenshot 2023-04-28 at 1 42 01 pm" src="https://user-images.githubusercontent.com/7619810/235065307-e09e6f20-4fc8-4120-8be0-19ca1e142b4a.png">

Initial version of the game concept which includes:
- [x] Can be passed or failed
- [x] Type in a letter with the keyboard and submit with a button
- [x] Mystery word is randomised from a static list
- [x] Optional: Can submit the letter using the "Enter" key
- [x] Animation of Po the cat falling with every incorrect answer 😅

Note: Testing has not been setup for this version

2023-05-01 06:48 UTC, HookyQR requested changes
Needs a tidy up before progressing.

- Use object spread where you can.
- Get rid of the inline styles. You can have more than one style sheet if you want to seperate thing in some objective way.

Everything else for a later task.

2023-05-01 06:48 UTC, HookyQR commented on src/App.js
> +        />
It's 2023 and we have [object spread](https://devdocs.io/javascript/operators/spread_syntax) available.
```react
        <Intro {...{guessAttempts}} />
        <HangmanGame
          {...{words, guesses, guessAttempts, setGuesses, fails, setFails}}
        />
```

2023-05-01 06:48 UTC, HookyQR commented on src/components/GuessInput.jsx
> +      }}
Why do half the things have inline styles, and there's also a stylesheet?

2023-05-01 06:48 UTC, HookyQR commented on src/components/HangmanGame.jsx
> +        guesses={guesses}
This is a butt load of prop drilling. We'll work on getting rid of this later.

2023-05-01 06:48 UTC, HookyQR commented on src/components/Illustration.jsx
> +    livesLeft && setPoImage(imgs[livesLeft - 1]);
If you had just added something for 7, you wouldn't need the guard clause.

2023-05-01 06:48 UTC, HookyQR commented on src/components/Illustration.jsx
> +      ) : (
This is one thing

2023-05-01 06:48 UTC, HookyQR commented on src/components/Illustration.jsx
> +      />
This is a whole other thing.

2023-05-01 06:48 UTC, HookyQR commented on src/components/Illustration.jsx
> +}
Can I suggest a change to the way you're running this string?

Have one image, that has the top part - including the break and the dangly bit - and change both the viewport, and the height based on the lives used. This will reveal the dangle length as the failures mount.

That way you can have a single SVG for the cat and the trailing string, and just move it down. It's ok IMO to have a break at the start, as that indicates the peril he is in.

So you should be able to do this with 2 SVGs, and not have to rely on a hidden image for the final part.

2023-05-01 06:48 UTC, HookyQR commented on src/styles/index.css
> +  font-family: "Inter", sans-serif;
This font is terrible on my screen. I don't care, just letting you know. Stick with the standards where you can (which you can here). They're standard for reasons.

2023-05-04 03:39 UTC, CoreyGinnivan commented on src/components/Illustration.jsx
> +}
This was a good call, awesome thinking! I was originally thinking that I was gonna change Po's facial expression too, but never jumped back in, but that could still be achieved this way inside the svgs - you the man

2023-05-04 03:39 UTC, CoreyGinnivan commented
@HookyQR Round of feedback all done 🙌

2023-05-05 01:07 UTC, HookyQR requested changes
On track to something we can work with. Drop these case statements for array lookups.

2023-05-05 01:07 UTC, HookyQR commented on src/components/illustrations/BottomRope.jsx
> +  };
You're using a case statement for an array lookup.
```js
viewBoxMaskHeight = heights[livesLeft] || defaultHeight
```

2023-05-05 01:07 UTC, HookyQR commented on src/components/illustrations/TopRope.jsx
> +  const viewBoxMaskHeight = () => {
Same here

2023-05-09 07:54 UTC, HookyQR commented on src/components/illustrations/BottomRope.jsx
> +  ];
```js
  const heights = [397, 393, 393, 392, 390, 389, 389];
```
Feels a little nicer. 😉

2023-05-09 09:24 UTC, CoreyGinnivan commented on src/components/illustrations/BottomRope.jsx
> +  ];
Derp haha 🙏

2023-05-10 00:18 UTC, HookyQR commented on src/components/illustrations/BottomRope.jsx
>    const viewBoxMaskHeight = heights[livesLeft]?.height || defaultHeight;
You have to change this too. Did you run the app?

2023-05-10 02:07 UTC, HookyQR approved these changes

2023-05-10 02:08 UTC, merged