Setup tests for the guess input submission
CoreyGinnivan/devtrain pull request #3
Opened 2023-05-10 09:02 UTC by CoreyGinnivan

Setup initial tests for the handling of guesses

2023-05-11 07:48 UTC, HookyQR requested changes
DRY time. Even in tests we don't want too much repetition. It distracts from the focus of the test.

Also, you lost one of you handling cases. What up with that?

2023-05-11 07:48 UTC, HookyQR commented on src/components/GuessInput.jsx
> +          disabled={isDisabled ? true : false}
The worlds most useless ternary:
```js
isDisabled = true  // => disabled == true
isDisabled = false // => disabled == false
```

How about just
```js
disabled={isDisabled}
```

https://eslint.org/docs/latest/rules/no-unneeded-ternary

2023-05-11 07:48 UTC, HookyQR commented on src/components/GuessInput.jsx
> +    if (guesses.includes(inputLetter)) {
What happens if I hit enter and it's empty?

2023-05-17 02:08 UTC, CoreyGinnivan commented on src/components/GuessInput.jsx
> +    if (guesses.includes(inputLetter)) {
Good call! I threw myself off while going down the test-creating path, thinking that it could never be invoked because the button was disabled, but completely forgetting that "Enter" is on the input, rather than triggering the button 🤪 - added back in, and added a test to cover it

2023-05-17 02:16 UTC, CoreyGinnivan commented
@HookyQR Ok did all those things, and also cleaned up a few other tests while in there. Like switching `expect(setFails).toHaveBeenCalled();` with `expect(setFails).toHaveBeenCalledWith(3);` to check we're actually getting the proper number back rather than just calling

2023-05-19 07:55 UTC, HookyQR approved these changes
Nice work. Merge that puppy and I'll give you something to ponder as the next task. 👿

2023-05-19 08:51 UTC, merged