Hangman game/refactor
CoreyGinnivan/devtrain pull request #5
Opened 2023-05-25 05:17 UTC by CoreyGinnivan

- Moved core functionality from GuessInput into HangmanGame
- Created main HangmanGame tests, and added new coverage for added functionality
- Updated GuessInput tests to cover what's controlled inside the component

Resolves #4

2023-05-25 05:34 UTC, HookyQR requested changes
Looking better. Now give `GuessInput` back it's letter to handle. 😉

2023-05-25 05:34 UTC, HookyQR commented on src/components/GuessInput.jsx
> +export function GuessInput({ addGuess, inputLetter, setInputLetter }) {
This should still handle `inputLetter` internally. That's its one job. It should call `addGuess` with `inputLetter` (currently called with nothing)

2023-05-25 05:34 UTC, HookyQR commented on src/components/GuessInput.jsx
> +export function GuessInput({ addGuess, inputLetter, setInputLetter }) {
A nice wrapper inside this component would help:

```js
export function GuessInput({ addGuess }) {
  const onClick = () => addGuess(inputLetter)
  // ...
          if (event.key === "Enter") { onClick() }
  // ...
        <button {...{className: "guessinput__submitbutton", onClick, disabled}} >
```

Which brings me to `isDisabled`. Is there any reason this isn't just `disabled`? Doesn't make it any less readable, and makes it easier to use. Not like you've got an `isntDisabled` lying around that you need to contrast with.

2023-05-25 05:34 UTC, HookyQR commented on src/components/__tests__/hangman_game.test.jsx
> +        const alert = (global.alert = jest.fn());
You shouldn't have to set `const alert` here. `alert` === `global.alert` unless defined somewhere in the scope.

2023-05-25 05:34 UTC, HookyQR commented on src/components/__tests__/hangman_game.test.jsx
> +    it("needs to have a masked word and render same amount of blank spaces", () => {
```suggestion
    it("has a masked word and render same amount of blank spaces", () => {
```
Be present. Be one with your tests.

<img src="https://media0.giphy.com/media/65ODDoEMHM5wbGDHWT/giphy.gif"/>

2023-05-25 07:57 UTC, CoreyGinnivan commented on src/components/GuessInput.jsx
> +export function GuessInput({ addGuess, inputLetter, setInputLetter }) {
@HookyQR A lil confused with this one 😬 so I'm keeping the function of `addGuess` still in the main game, but I'm putting the state management back inside the GuessInput component? `const [inputLetter, setInputLetter] = useState("");`

2023-05-25 08:01 UTC, CoreyGinnivan commented on src/components/GuessInput.jsx
> +export function GuessInput({ addGuess, inputLetter, setInputLetter }) {
Think I just had to rubber duck it 😅

2023-05-25 08:05 UTC, HookyQR commented on src/components/GuessInput.jsx
> +export function GuessInput({ addGuess, inputLetter, setInputLetter }) {
addGuess belongs to the game. All things pertaining to the current letter belong to `GuessInput`. (Doesn't become part of the game's data until it is submitted)

<img src="https://media1.giphy.com/media/u6abG1EmZciv6/giphy.gif"/>

2023-05-26 05:11 UTC, HookyQR commented
You know what. The one message I didn't get was the review request. 🤦

2023-05-26 05:16 UTC, HookyQR requested changes
Getting closer.

<img src="https://media0.giphy.com/media/FsYSGfMcJBAZ1LoBp3/giphy.gif"/>

2023-05-26 05:16 UTC, HookyQR commented on src/components/GuessInput.jsx
> +export function GuessInput({ addGuess, inputLetter, setInputLetter }) {
The signature of this component should be:
```
GuessInput({ addGuess })
```
It should contain the `inputLetter` management in its entirety. The game does not need, and should not want anything to do with the 'input'. Only the 'guess'.

2023-05-29 07:06 UTC, HookyQR requested changes
Too much knowledge being passed around.

2023-05-29 07:06 UTC, HookyQR commented on src/components/GuessInput.jsx
> +  const onClick = () => addGuess(inputLetter, setInputLetter);
```js
  const onClick = () => addGuess(inputLetter);
```

The `setLetterGuess` at the end is not required. There's no need to clear that input, as any other input will clear it for you. If you really think that's required, you can just:

```js
  const onClick = () => {
    addGuess(inputLetter);
    setInputLetter("");
  }
```

I'll say it again... The game does not need to know how the input works. It only has to handle the submission of a guess, just the letter. Not handle what happens to the input box after the fact, no handle clearing the stored input. It does not, and should not care where the letter comes from or how, `addGuess` takes a letter and updates the _game state_ with it, that is all.

2023-05-29 07:06 UTC, HookyQR commented on src/components/HangmanGame.jsx
> +  function addGuess(letterGuess, setLetterGuess) {
You're being a little too verbose. A `letter` and a `guess` are the same thing coming in to this function, no need to call it both things. Pick one. 😉

2023-05-29 07:06 UTC, HookyQR commented on src/components/HangmanGame.jsx
> +        <GuessInput {...{ addGuess }} />
Better, but you're just passing the knowledge back up now, as apposed to passing it down like you were before.

The game does not need to know about how a letter is created or cleared. It just needs the letter once it is ready.

2023-06-06 08:55 UTC, HookyQR approved these changes
Yep, let's do it. Don't forget to get rid of the `backspace`/`delete` handling on the cleanup PR. (AND TEST FIRST!!)

2023-06-08 04:21 UTC, merged