Big cleanup
CoreyGinnivan/devtrain pull request #6
Opened 2023-06-13 06:19 UTC by CoreyGinnivan

2023-06-14 02:37 UTC, HookyQR requested changes
Couple of notes. Coverage is looking decent.

2023-06-14 02:37 UTC, HookyQR commented on src/components/GameOverScreen.jsx
> +      className: "guessinput__submitbutton",
Feel like the tree style naming is still working for you? 😜
Just `submit` should be enough. Also, does it even need a class? How many buttons are there? What's wrong with `button {}` in your css?

2023-06-14 02:37 UTC, HookyQR commented on src/components/GameOverScreen.jsx
> +};
One liners for the win when using Arrow functions.

Formatter will turn it in to 3 lines still, but the implicit return is better as it shows that there is no work happening here.

Also, you're doing the ternary inside of the `JSX`, no need for that:
```js
<>{lost ? <GameOverLoss /> : <GameOverWin />}</>
```
❌
```js
lost ? <GameOverLoss /> : <GameOverWin />
```
✅

2023-06-14 02:37 UTC, HookyQR commented on src/components/GuessInput.jsx
> +    addGuess(inputLetter.toLowerCase());
Why are we lowerCase'ing still? It's not needed.

2023-06-14 02:37 UTC, HookyQR commented on src/components/GuessInput.jsx
> +    if (/^[a-zA-Z]*$/.test(input)) {
Since you only care about the last letter, you should only test the last letter: `/[a-zA-Z]$/`.

2023-06-14 02:37 UTC, HookyQR commented on src/components/GuessInput.jsx
> +        value={inputLetter ?? ""}
Nice. Don't get to see that much. `||` would give you the same result btw.

2023-06-14 02:37 UTC, HookyQR commented on src/components/GuessInput.jsx
>          onKeyDown={(event) => {
This is still an inline method definition here. Put it in the component, but outside of the `JSX`. `onKeyDown={onKeyDown}`

2023-06-14 02:37 UTC, HookyQR commented on src/components/HangmanGame.jsx
> +    if (!word.includes(guess)) {
This is what locks you in to your case sensitivity.

You can do the case change for both here:
```js
word.toLowerCase().includes(guess.toLowerCase())
```

2023-06-14 02:37 UTC, HookyQR commented on src/components/HangmanGame.jsx
> +    if (!word.includes(guess)) {
Alternatively, use a regex like the one you build above, but with `word`.

2023-06-14 02:37 UTC, HookyQR commented on src/components/GuessInput.jsx
>          onBlur={({ target }) => target.focus()}
Is also inline. This one can be pulled out of the component completely as it has no dependancy on the component itself.

2023-06-14 02:37 UTC, HookyQR commented on src/components/GameOverScreen.jsx
> +    <SubmitButton message="Play Again" />
`message` is really `children`:
```js
<SubmitButton>Play Again</SubmitButton>
```

2023-06-14 03:15 UTC, CoreyGinnivan commented on src/components/GuessInput.jsx
> +    if (/^[a-zA-Z]*$/.test(input)) {
I think I have to leave this one as the same, switching it over breaks backspace from working

2023-06-14 06:01 UTC, CoreyGinnivan commented on src/components/GameOverScreen.jsx
> +      className: "guessinput__submitbutton",
I guess it was more just future-proofing if another button existed down the line. I'll go with submit because I still like being explicit and not applying it directly to elements 😅

2023-06-14 06:11 UTC, CoreyGinnivan commented on src/components/GuessInput.jsx
> +    if (/^[a-zA-Z]*$/.test(input)) {
It also breaks the tests 😀 yayyy

2023-06-15 01:13 UTC, HookyQR commented on src/components/HangmanGame.jsx
> +    setGuesses(updateGuesses(guess));
This is not what I meant.

Instead of passing `setGuesses` to this component, pass `updateGuesses`, that will make it testable.
```js
expect(updateGuesses).to.haveBeenCalledWith('l')
```

You're actually doing the same thing here that you were doing before. You're calling `setGuesses` with the recomputed array which relies on the current value. Which is a no-no. `setGuesses` should receive the _function_ not the result of that function. See https://react.dev/reference/react/useState#updating-state-based-on-the-previous-state

2023-06-15 01:17 UTC, HookyQR commented on src/components/HangmanGame.jsx
> +  }
Use a `let` since you're changing the whole value:
```js
  let wordstyle = {
    color: "black",
    backgroundColor: "transparent",
    borderColor: "#e0e0e0",
  };

  if (won) {
    wordstyle = {
      color: "white",
      backgroundColor: "green",
      borderColor: "green",
    }
  }
```

Also, this is the perfect place to use a class instead:
```js
<p {...{ className: `word ${won ? 'won' : 'lost'}` }}>{maskedWord}</p>
```

2023-06-15 01:57 UTC, HookyQR commented on src/components/HangmanGame.jsx
> +  }
Or `won` & `active` 🤷

2023-06-15 06:49 UTC, HookyQR reviewed
Looking better, keep it up.

For the part that you're circling around, you want to change the component's signature to:
```js
export default function HangmanGame({
  words,
  guesses,
  guessAttempts,
  updateGuess, // not set setGuesses here, should just receive a single letter
  fails,
  setFails,
})
```
Note that you won't be able to test that `guesses` was updated, but that's not `HangmanGame`'s job, its job is to advise that a (validated) guess was made in this situation, that is all.

2023-06-15 06:49 UTC, HookyQR commented on src/components/GuessInput.jsx
> +      return setInputLetter(input.at(-1));
No need to `return` this, as we're not stopping anything from happening further down. Doesn't matter though.

2023-06-15 06:49 UTC, HookyQR commented on src/components/GuessInput.jsx
> +    }
Since you have a guard clause, you should move it above the thing you're guarding. (`regex` and `matches` are useless if this return happens.)

2023-06-15 06:49 UTC, HookyQR commented on src/components/HangmanGame.jsx
> +          className: `word ${won && "word--won"}`,
👍

2023-06-20 04:25 UTC, HookyQR approved these changes
Nice work. Coverage looks great.

2023-06-20 06:53 UTC, merged