Hangman game/custom hooks gameplay
CoreyGinnivan/devtrain pull request #8
Opened 2023-06-26 03:53 UTC by CoreyGinnivan

- [x] - Moved game logic in to hook for convenience 
- [x] - Created new hook for random word selection
- [x] - Created data file for words to simplify app
- [x] - Cleaned up/simplified file structure as well as component naming
- [x] - Added tests for full coverage

2023-06-26 04:42 UTC, HookyQR requested changes
Nice start. That's the right way to test a hook. 👍 

There are a couple of logic decisions lingering outside the game engine though.

Deciding the colour of a letter should be based on its state, not calculated against the word (that's game logic). 

I've got a couple of other thing too, but their best kept seperate from this first review.

2023-06-26 04:42 UTC, HookyQR commented on src/components/__tests__/hangman_logic.test.jsx
> +import { mount } from "enzyme";
This is all correct, but it should be in `hooks/__tests__/useHangman.test.jsx`.

2023-06-26 04:42 UTC, HookyQR commented on src/components/__tests__/hangman_logic.test.jsx
> +        <GameOver {...{ lost }} />
No need to invoke `GameOver` could have just
```js
<div id="won">{won && 'yes'}</div>
```
etc.

2023-06-26 04:42 UTC, HookyQR commented on src/components/__tests__/hangman_logic.test.jsx
> +        <GuessInput {...{ makeGuess }} />
Same here, no need to invoke real objects, could just add an input that calls `makeGuess` on update. You control all the data here, so you don't have to worry about validation. This will make your tests much easier to read.

2023-06-26 04:42 UTC, HookyQR commented on src/hooks/useRandomWord.jsx
> +import { useEffect, useState } from "react";
No tests for you!! 🤷‍♂️😢

2023-06-26 04:42 UTC, HookyQR commented on src/components/HangmanGame.jsx
> +  const { guesses, won, lost, fails, guessAttempts, maskedWord, makeGuess } =
Note that `fails` is never actually used on its own. Returning `livesLeft` here will bring that last little bit of logic back. `GuessedLetters` can take a `done: won || lost` instead of working it out a second time.

2023-06-26 04:42 UTC, HookyQR commented on src/hooks/useHangman.jsx
> +  function makeGuess(guess) {
I see you've moved the validation in here already. Nice.

2023-06-26 04:42 UTC, HookyQR commented on src/components/__tests__/layout.test.jsx
> +    it("has the correct class", () => {
```js
expect(component.find('div')).toHaveClassName('game')
```
is better. Use the enzyme jest matchers where they exist. You should be able to read it almost like regular English.

It's rare that you would need to use `toBe(true)` in a component spec.

2023-06-26 04:42 UTC, HookyQR commented on src/hooks/useHangman.jsx
> +  const won = !maskedWord.includes("_");
```js
  const won = maskedWord == word;
```

2023-06-26 04:42 UTC, HookyQR commented on src/hooks/useRandomWord.jsx
> +    const randomIndex = Math.floor(Math.random() * words.length);
Just `index` will do, you're already in `useRandomWord`, and using `random` on this line. It's possible to be over explicit.

2023-06-26 04:42 UTC, HookyQR commented on src/hooks/useRandomWord.jsx
> +export { useRandomWord };
I suggest exporting hooks as the `default`. Forces you to keep it as one logic mechanism per file.

2023-06-26 04:42 UTC, HookyQR commented on src/components/__tests__/guess_input.test.jsx
> +    });
What if the input is empty and the button is clicked? Does it call `makeGuess` then?

2023-06-26 04:42 UTC, HookyQR commented on src/components/__tests__/guessed_letters.test.jsx
> +  });
Although it just seems like a display decision, `GuessedLetters` is making logic decisions here. Suggest changing the structure of `guesses` to include the right/wrong state:
```js
guesses = {h: 'right', r: 'wrong'}
// or
guesses = [{letter: 'h', result: 'right'}, {letter: 'r', result: 'wrong'}]
```
Both of these can be mapped easily. I suggest the first option myself.

2023-06-27 01:58 UTC, CoreyGinnivan commented on src/hooks/useHangman.jsx
> +  const won = !maskedWord.includes("_");
🤦‍♂️

2023-06-27 09:59 UTC, HookyQR requested changes
Still stepping our way there. Don't rush, look stuff up if you find yourself doing the same thing for different circumstances (`toBe(true)`).

2023-06-27 09:59 UTC, HookyQR commented on src/components/GuessedLetters.jsx
> +    const colorClass = isCorrect ? "right" : "wrong";
```js
    const colorClass = guesses[letter];
```

Note there is no need for any temp var at all.
```js
Object.entries(guesses).map(([letter, className] => (
  <span key={letter} {...{className}}>{letter}</span>
)
```
See [Iterating through an object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#iterating_through_an_object)

2023-06-27 09:59 UTC, HookyQR commented on src/components/GuessedLetters.jsx
> +  });
Don't pre build react, put this straight in to the htmlish block. If you want it seperate, add a new component and build the paragraph (with this in it) inside it.

2023-06-27 09:59 UTC, HookyQR commented on src/components/HangmanGame.jsx
> +  const { guesses, won, lost, livesLeft, maskedWord, makeGuess } =
Note that `livesLeft==0` is the same as `lost`, but I think it's good to let the engine decide that.

2023-06-27 09:59 UTC, HookyQR commented on src/components/__tests__/game_over_screen.test.jsx
> +    });
Lets talk about white space...
```js
  describe("Game state", () => {
    describe("When the game is won", () => {

      it("has the success copy", () => {
        expect(component.find("h1")).toHaveText("You saved Po! Yayyyy");
      });
    });

    describe("When the game is lost", () => {
      const component = mount(<GameOver {...{ lost: true }} />);

      it("has the success copy", () => {
        expect(component.find("h1")).toHaveText(
          "You lose... To the void you go Po!"
        );
      });
    });
```

Much easier to see what's going on.

2023-06-27 09:59 UTC, HookyQR commented on src/components/__tests__/layout.test.jsx
> +  const component = shallow(<Layout>{child}</Layout>);
Since you're not referring to the child, there's no need to explicitly define it.
```js
  const component = shallow(
    <Layout><span className="test">Stuff</span></Layout>
  );
```

2023-06-27 09:59 UTC, HookyQR commented on src/components/__tests__/layout.test.jsx
>      });
Note that an `it` with a single expectation can be written without the `{}`:
```js

    it("can accept children", () => expect(component).toContainMatchingElement(".test")));
```
And don't forget to leave a blank line between your tests. Makes them easier to find/read.

And again, use the [enzyme matchers](https://github.com/enzymejs/enzyme-matchers/blob/master/packages/jest-enzyme/README.md).

2023-06-27 09:59 UTC, HookyQR commented on src/components/__tests__/useHangman.test.jsx
Move this file to `src/hooks/__tests__/useHangman.test.jsx`

2023-06-27 09:59 UTC, HookyQR commented on src/components/__tests__/useHangman.test.jsx
> +          <button onClick={handleButtonClick}>Submit</button>
You shouldn't need the button. Since you (the test) control this, you can do it all in the `onChange` event (move it out to where the click handler is though)

2023-06-27 09:59 UTC, HookyQR commented on src/components/__tests__/useRandomWord.test.jsx
> +    ).toBe(true);
```js
expect(words).toContain(randomWord)
```
Again, avoid the `toBe(true)`.

2023-06-27 09:59 UTC, HookyQR commented on src/hooks/useHangman.jsx
> +    updateGuesses({ ...guesses, [guessLetter]: guessResult });
This is using the non-safe version of the setter (use the updater version like you were before).

Also, you don't nee `pushGuess` any more, this logic can go directly in to the `makeGuess` function.

```js
{ ...guesses, [guessLetter]: word.includes(guess) ? 'right' : 'wrong' }
```

2023-06-27 09:59 UTC, HookyQR commented on src/hooks/useHangman.jsx
>      }
This also uses an unsafe updater.

2023-06-28 09:02 UTC, HookyQR approved these changes
Nice, merge as is, and I'll add an issue for the one remaining refactor (just to keep it out of this PR)

2023-06-28 09:06 UTC, merged